# Generated by Django 2.2.4 on 2020-03-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lead_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
