# Generated by Django 2.2.4 on 2020-03-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproject', '0002_team_lead_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='contact_no',
            field=models.IntegerField(),
        ),
    ]
