# Generated by Django 2.2.4 on 2020-03-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproject', '0005_auto_20200326_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
