# Generated by Django 2.2.4 on 2020-04-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproject', '0006_auto_20200326_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, upload_to='profile_image'),
        ),
    ]
